apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-indicators
  namespace: ben
  labels:
    app: technical-indicators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technical-indicators
  template:
    metadata:
      labels:
        app: technical-indicators
    spec:
      imagePullSecrets:
        - name: ghcr-creds

      containers:
      - name: technical-indicators
        image: ghcr.io/benitomartin/technical_indicators:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "candles"
        - name: KAFKA_OUTPUT_TOPIC
          value: "technical_indicators"
        - name: KAFKA_CONSUMER_GROUP
          value: "technical_indicators_group"
        - name: CANDLE_SECONDS
          value: "60"

        resources:
          requests:
            memory: 512Mi
            cpu: "250m"
          limits:
            memory: 1Gi
            cpu: "500m"
