apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles
  namespace: rwml
  labels:
    app: candles
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candles
  template:
    metadata:
      labels:
        app: candles
    spec:
      containers:
      - name: candles
        # Replace with the exact tag from your build output
        image: ghcr.io/benitomartin/candles:0.1.5-beta.1710234567
        imagePullPolicy: Always # Make sure to pull the latest images from the github container registry
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-c6c8-kafka-bootstrap.strimzi.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "trades"
        - name: KAFKA_OUTPUT_TOPIC
          value: "candles"
        - name: KAFKA_CONSUMER_GROUP
          value: "candles_consumer_group"
        - name: CANDLE_SECONDS
          value: "60"
